<html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
<script src="stylesheets/jquery/jquery-3.5.1.js"></script>
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="stylesheets/bootstrap/css/bootstrap.min.css"/>

<!-- Boostrap JS -->
<script src="stylesheets/bootstrap/js/bootstrap.min.js"></script>

<link rel="stylesheet" href="stylesheets/main.css">

<title>
    <?php
        $pageTitle = "";
        echo $_pageTitle;
    ?>
</title>

</head>
<body>
<center>
<?php
    include('includes/header.inc');
?>

