<center>
    <nav class="navbar justify-content-center bg-dark">
        <a href="admin_home.php"><h3 class="text-white">Admin panel: <?php echo $_SESSION['username']; ?></h3></a>
        <a  class="btn btn-dark" href="admin_home.php">My Images</a>
        <a  class="btn btn-dark" href="add_image.php">Add image</a>
        <a  class="btn btn-dark" href="my_account.php">Manage account</a>
        <a  class="btn btn-dark" href="logout.php">Log Out</a>
    </nav>
</center>