<center>
    <nav class="navbar justify-content-center bg-dark">
        <h3 class="text-white">Gallery Hub</h3>
        <a class="btn btn-dark" href="index.php">Home</a>
        <a class="btn btn-dark" href="gallery.php">Gallery</a>
        <a class="btn btn-dark" href="members.php">Members</a>
        <a class="btn btn-dark" href="register.php">Register</a>
        <a class="btn btn-dark" href="login.php">Log in</a>
    </nav>
</center>